### PR TITLE
hide the unsafe Peripheral::new constructor

### PR DESCRIPTION
**Pull request by japaric**
`peripherals!` is the safe way to declare `Peripheral`s

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 840c320 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 840c320 with merge 840c320...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/225827666)
Approved by: japaric
Pushing 840c32060bcf3127dab77c321c3c63ebffabcee9 to master...

**Pull request merged**
