### PR TITLE
fix documentation link

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d8eb3ea has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d8eb3eac75ade47e07dae96fd1ab772f1983c233 with merge 716fb9ba147a8888cfd391fa83c80e2c554e11b2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/329254034?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 716fb9ba147a8888cfd391fa83c80e2c554e11b2 to master...

**Pull request merged**
