### PR TITLE
add a `peripherals` macro

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3ffc47a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3ffc47a with merge 3ffc47a...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f9ada3f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f9ada3f with merge f9ada3f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/225799790)
Approved by: japaric
Pushing f9ada3f7f45c1370b38a369a64dca4535cdb543c to master...

**Pull request merged**
