### PR TITLE
Fix "Could not find `Op` in `proc_macro`"

### PR DESCRIPTION
**Pull request by chocol4te**
Fixes nightly error with `proc-macro2`. 

Should not be merged until https://github.com/japaric/rtfm-syntax/pull/8 is merged and new `rtfm-syntax` version is published.

### CODE REVIEW

**Comment by little-arhat** [comment]
This is addressed in `tq` branch as well, I belive (see https://github.com/japaric/cortex-m-rtfm/commit/7b598c0749aa5390cfefc8e138c05fafa7599dc6). But it would be nice to have it in master!

**Comment by chocol4te** [comment]
Sorry, my bad, I didn't check other branches

**Comment by little-arhat** [comment]
@chocol4te no worries, as far as I know, `tq` branch has other, quite significant changes, so it would be nice to backport just compatibility changes to master, as it's not clear (for me, at least) whether and when `tq` will be merged.

**Comment by MabezDev** [comment]
I have a working version of rtfm for the latest cortex-m-rt [here](https://github.com/MabezDev/cortex-m-rtfm). It's not perfect though, systick can't be used as an interrupt source.

**Comment by japaric** [comment]
Thanks @chocol4te!

bors r+

**Pull request closed without merging**
