### PR TITLE
make the ceiling part of the task signature

### PR DESCRIPTION
**Pull request by japaric**
remove the P.as_ceiling method

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e2bde8d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e2bde8d with merge e2bde8d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/226648680)
Approved by: japaric
Pushing e2bde8d21acdfb845554d960536bfb94a7bb1f86 to master...

**Pull request merged**
