### PR TITLE
preemption threshold token, tweak Resource Sync-ness

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit acdfa6f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit acdfa6f with merge acdfa6f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/230067760?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing acdfa6f09d27fea43926e1d286f13f27a811a203 to master...

**Pull request merged**
