### PR TITLE
safe `&'static mut` references via init.resources

### PR DESCRIPTION
**Pull request by japaric**
see RFC #59 for details

### CODE REVIEW

**Comment by japaric** [comment]
Depends on both japaric/rtfm-syntax#2 and japaric/rtfm-core#3

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 88f5053 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 88f505369c50fa2261ccad3a929ee180cd601fad with merge 5991581c893b2acba7b41c15a2c7af9cf7075154...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/320605704?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a238fd5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a238fd5dc783f57f8fa61795690e6069b1becd32 with merge 8a396c51f2caaeca7ee0f81ef2f3c4f2f73d8df1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/320610268?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 8a396c51f2caaeca7ee0f81ef2f3c4f2f73d8df1 to master...

**Pull request merged**
