### PR TITLE
rename `rtfm::critical` to `rtfm::atomic`, touch up the documentation

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 404dde6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 404dde6 with merge 404dde6...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aa0347e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aa0347e with merge aa0347e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/225852137)
Approved by: japaric
Pushing aa0347e36c5ab67fa3153cb91d32a2aeea840223 to master...

**Pull request merged**
