### PR TITLE
make `as_ceiling` a general method of `P<N>`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ec2df60 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ec2df60 with merge ec2df60...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/226619310)
Approved by: japaric
Pushing ec2df608ca4c35f044c383b7a4c8ba268657aa15 to master...

**Pull request merged**
