### PR TITLE
fix `idle::Resources::new`

### PR DESCRIPTION
**Pull request by japaric**
it assumed that all resources were "early" resources

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2415a64 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2415a64 with merge 2415a64...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/282236100?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c184f91 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c184f91 with merge c184f91...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/282243809?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c184f91e3c3993dacbd8425019cde6a3607478bc to master...

**Pull request merged**
