### PR TITLE
Fix to make all work with cortex-m 0.6.0

### PR DESCRIPTION
**Pull request by korken89**

### CODE REVIEW

**Comment by korken89** [comment]
With this it should be compatible with the new `cortex-m` version. r? @TeXitoi @japaric

**Comment by japaric** [comment]
This is no longer necessary as cortex-m is using the semver trick to let v0.5.x and v0.6.x interoperate.

I would prefer to keep the version requirement as it is (i.e. specifying the minimum minor version rather than a minor version range).

**Comment by TeXitoi** [comment]
@korken89 can we close this?

**Comment by korken89** [comment]
Sure, I think we are ok

**Comment by burrbull** [comment]
`cargo tree` doesn't work with cortex-m 0.5.8
```
error: no matching package named `cortex_m_0_6` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `cortex-m v0.5.10`
    ... which is depended on by `cortex-m-rtfm v0.5.0-alpha.1 (https://github.com/japaric/cortex-m-rtfm#fafeeb27)`
```

**Pull request closed without merging**
