### PR TITLE
make resource proxies not Sync

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 62c5c1a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 62c5c1ae431790e36ffeb0eebba75dfabb5dbd76 with merge 0f5784c2401d4b12004f34345e721598fa21219a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/313983871?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0f5784c2401d4b12004f34345e721598fa21219a to master...

**Pull request merged**
