### PR TITLE
add a Cargo feature, cm7-r0p1, to fix a Cortex-M7 BASEPRI erratum

### LINKED ISSUE #53: work around Cortex-M7 BASEPRI erratum
See erratum 837070 in "ARM Processor Cortex-M7 (AT610) and Cortex-M7 with FPU (AT611), Product revision r0, Sofware Developers Errata Notice".

Basically the problem is that `msr BASEPRI` won't immediately take effect and the instruction following it won't have the new / desired dynamic priority and thus it can be preempted as if BASEPRI hadn't been modified.

The suggested workaround is to temporarily disable interrupts when `msr BASEPRI` is issued, so basically something like this:

``` armasm
cpsid i
msr BASEPRI
cpsie i
```

We can directly apply this fix in claim since claim only modifies BASEPRI when interrupts are enabled. (If interrupts are disabled, claim is a no-operation) 

However, It would be ideal if we only applied this fix when targeting Cortex-M7 devices. And I think we can do that but we'll need some help from svd2rust. SVD files contains these `<cpu>` and `<revision>` fields that would let us identify chips with the problem. Device crates could expose `CPU` and `REVISION` constants that claim could check to decide whether to apply the workaround or not.

Thanks @pftbest for reporting this.
cc @perlindgren

### PR DESCRIPTION
**Pull request by japaric**
closes #53
alternative solution to #54
depends on japaric/cortex-m#72

### CODE REVIEW

**Comment by japaric** [comment]
Closing in favor of japaric/cortex-m#72

**Comment by japaric** [comment]
Whoops, closed the wrong PR

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6e3b9a3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6e3b9a30fd9816963813d505265b6b0fcc8951c7 with merge b93f8552a0b2e8774dc06cc1c474b48c61553b3f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/327718610?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f695bdb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f695bdb7e9dab1af3964ddabccf9c738dd46d774 with merge dd12a6a14d2bb028c8da96cb510b67de31d28be4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/327722272?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing dd12a6a14d2bb028c8da96cb510b67de31d28be4 to master...

**Pull request merged**
