### PR TITLE
specify both the path and version of the cortex-m-rtfm-macros dependency

### PR DESCRIPTION
**Pull request by japaric**
this seems to be required for cargo publish to Just Work

cc @jonas-schievink

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bf94be9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bf94be9f7ee272ac7e03147e5ae2320dda0ed57e with merge d0970211f7105b9d9a0527bd23fa2cb0f4eb8ab6...

**Comment by jonas-schievink** [comment]
Indeed, this is even documented here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/329258628?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d0970211f7105b9d9a0527bd23fa2cb0f4eb8ab6 to master...

**Pull request merged**
