### PR TITLE
make resource proxies !Send

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8f23fdc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8f23fdc9340167cf9d6d31a09705369c3b8acccb with merge e4826208dd6c9a33b0aec3b7fc57d7dcc2af8b4f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/313966903?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d6c240f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d6c240f9743067c81e68adcf35c60304573db8b9 with merge 40ebb93cc6ec8533d4532853c3fd01693af09d8e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/313970657?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 40ebb93cc6ec8533d4532853c3fd01693af09d8e to master...

**Pull request merged**
