### PR TITLE
update examples

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2063697 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2063697 with merge 2063697...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/226833995?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2063697c626a7547f5d9fb140fbc7eb9773a5120 to master...

**Pull request merged**
