### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e90cf07 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e90cf07dd6785a34cbece152adc57dfcb3fbdd80 with merge 896a01eeef029313f18d0269e08a5c6dc6b767f3...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/305689559?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cdb2118 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cdb2118cd36f8bfbdb7e296580cae05d6291bc5d with merge 99df0776c68fdb377ef7daa34f7fd8481fea590f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/305695111?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 99df0776c68fdb377ef7daa34f7fd8481fea590f to master...

**Pull request merged**
