### PR TITLE
fix cfail tests

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8e523d0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8e523d036c83fff35182d2fc50d042da866982a7 with merge 5ae8fd2965cdcca5a4df917d0a789bdc484a62db...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/313463484?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 815c3d9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 815c3d960d74c1d7c304b1f8c4040d704c19eb7b with merge e620b1e57a39f342cf73ad6ac8ab0e179b97bfd5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rtfm/builds/313466798?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e620b1e57a39f342cf73ad6ac8ab0e179b97bfd5 to master...

**Pull request merged**
